data:
  charges_path: 's3://bcg-case-study/data/charges.csv'
  damages_path: 's3://bcg-case-study/data/damages.csv'
  endorse_path: 's3://bcg-case-study/data/endorse.csv'
  primary_person_path: 's3://bcg-case-study/data/primary_person.csv'
  restrict_path: 's3://bcg-case-study/data/restrict.csv'
  units_path: 's3://bcg-case-study/data/units.csv'

  
